name: Build zally

on:
  push:
  workflow_dispatch:

env:
  ZALLY_VERSION: v2.1.1

jobs:
  build-vehub-zally-api-linter:
    runs-on: ubuntu-latest

    # Checkout
    steps:
      - uses: actions/checkout@v4

      - name: Download
        working-directory: ./bin
        run: |
          ./download.sh

      - name: Build server image
        working-directory: ./bin
        run: |
          ./build.sh
