on:
  release:
    types: [created]

env:
  ZALLY_VERSION: v2.1.1

jobs:
  build-cli:
    name: Release CLI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: "arm64"
            goos: windows

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download
        working-directory: ./bin
        run: |
          ./download.sh

      - name: Build server image
        working-directory: ./bin
        run: |
          ./build.sh

      - name: Build server
        id: docker_server_build
        uses: docker/build-push-action@v4
        with:
          context: ./iac/images/server
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            pharndt/zally-server:latest
            pharndt/zally-server:${{env.ZALLY_VERSION}}

      - name: Build Web UI
        id: docker_web_ui_build
        uses: docker/build-push-action@v4
        with:
          context: ./iac/images/web-ui
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            pharndt/zally-web-ui:latest
            pharndt/zally-web-ui:${{env.ZALLY_VERSION}}
