on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write


env:
  ZALLY_VERSION: v2.1.1


jobs:
  build-cli:
    name: Release CLI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: "arm64"
            goos: windows

    steps:
      - uses: actions/checkout@v4

      - name: Download
        working-directory: ./bin
        run: |
          ./download.sh

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
          project_path: "./bin/zally/cli/zally"
          binary_name: "zally"
