on:
  release:
    types: [created]

env:
  ZALLY_VERSION: v2.1.1

jobs:
  build-cli:
    name: Release Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download
        working-directory: ./bin
        run: |
          ./download.sh

      - name: Build server image
        working-directory: ./bin
        run: |
          ./build.sh
          docker tag zally-server pharndt/zally-server:latest
          docker tag zally-server pharndt/zally-server:${{env.ZALLY_VERSION}}

          docker tag zally-web-ui pharndt/zally-web-ui:latest
          docker tag zally-web-ui pharndt/zally-web-ui:${{env.ZALLY_VERSION}}
      - name: Push
        run: |
          docker push zally-server:latest
          docker push zally-server:${{env.ZALLY_VERSION}}

          docker push zally-web-ui:latest
          docker push zally-web-ui:${{env.ZALLY_VERSION}}
